estoquefacil/estoquefacil/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('materiais.urls')),
    path('admin/', admin.site.urls),
]

estoquefacil/materiais/urls.py
from django.urls import path
from . import views


app_name = 'materiais'
urlpatterns = [
    path('', views.index, name='index'),
    path('meuestoque/', views.meuestoque, name='meuestoque'),
    path('meuestoque/detalhe/<str:nome>', views.detailview, name='detalhe'),
    path('entrada/', views.entrada, name='entrada')
]

estoquefacil/materiais/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator


class Materiais(models.Model):
    material = models.CharField(max_length=300)
    datacompra = models.DateField()
    datavalidade = models.DateField()
    quantidade = models.IntegerField(validators=[MinValueValidator(0)])
    custo = models.FloatField(
        validators=[MinValueValidator(0.0)]
    )

    def __str__(self):
        return self.material

    def custo_unitario(self):
        cu = self.custo/self.quantidade
        return cu

    def dias_para_validade(self):
        dpv = self.datavalidade - timezone.now()
        return dpv

    def materiais_criticos(self):
        mc = self.datavalidade <= timezone.now() + datetime.timedelta(days=10)
        return mc

estoquefacil/materiais/forms.py
from django import forms
from .models import Materiais


class EntradaMateriais(forms.ModelForm):
    class Meta:
        model = Materiais
        fields = "__all__"

estoquefacil/materiais/views.py
from django.shortcuts import render
from .models import Materiais
# from django.http import HttpResponse
from .forms import EntradaMateriais
from django.shortcuts import redirect, reverse
from django.db.models import Sum


def index(request):
    return render(request, 'materiais/index.html')


def meuestoque(request):
    estoque = Materiais.objects.values('material').annotate(
        Sum('custo')).annotate(Sum('quantidade'))
    saldo = Materiais.objects.aggregate(total=Sum('custo'))
    return render(request, 'materiais/meuestoque.html',
                  {'estoque': estoque,
                   'saldo': saldo,
                   }
                  )


def detailview(request, nome):
    detail = Materiais.objects.filter(material=nome)
    return render(request, 'materiais/detalhe.html', {'detail': detail})


def entrada(request):
    if request.method == 'POST':
        form = EntradaMateriais(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('materiais:entrada'))
    else:
        form = EntradaMateriais()
    return render(request, 'materiais/entrada.html', {'form': form})

estoquefacil/materiais/templates/materiais/detalhe.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title></title>
  </head>
  <body>
    <table>
      <tr>
        <th>Material</th>
        <th>Quantidade</th>
        <th>Data Compra</th>
        <th>Custo</th>
      </tr>
      {% for materiais in detail %}
      <tr>
        <td>{{ materiais.material }}</td>
        <td>{{ materiais.quantidade }}</td>
        <td>{{ materiais.datacompra }}</td>
        <td>{{ materiais.custo }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

estoquefacil/materiais/templates/materiais/entrada.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title></title>
  </head>
  <body>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Adicionar" />
    </form>
  </body>
</html>

estoquefacil/materiais/templates/materiais/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title></title>
  </head>
  <body>
    <h1>Estoque Fácil | Empresa</h1>
    <div>
      <a href="{% url 'materiais:meuestoque'  %}">
        <strong>Meu Estoque</strong>
      </a>
    </div>
    <div>
      <a href="{% url 'materiais:entrada'  %}">
        <strong>Entrada de Materiais</strong>
      </a>
    </div>
    <div>
        <strong>Inventário</strong>
      </a>
    </div>
  </body>
</html>

estoquefacil/materiais/templates/materiais/meuestoque.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <title></title>
  </head>
  <body>
    <h1>Saldo Total: R$ {{ saldo.total }}</h1>
    <table>
      <tr>
        <th>Material</th>
        <th>Quantidade</th>
        <th>Custo</th>
      </tr>
      {% for materiais in estoque %}
      <tr>
        <td>
          <a href="/meuestoque/detalhe/{{ materiais.material }}">
            {{ materiais.material }}
        </td>
        <td>{{ materiais.quantidade__sum }}</td>
        <td>{{ materiais.custo__sum }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>